In [75]:
# 参考https://morvanzhou.github.io/tutorials/machine-learning/tensorflow/5-09-RNN3/
import pandas as pd
from sklearn import preprocessing
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [76]:
df_XWQY_CPXX = pd.read_table("./JXW_XWQYCPXX.txt",low_memory=False)

In [77]:
print(df_XWQY_CPXX.shape)
df_XWQY_CPXX.head(1)

(147005, 29)


ZH           MC DQ_S DQ_Q DQ_XZ   HYDM1    HYDM2            HYDM3  \
0  54218304  长兴艾尔诺纺织有限公司  湖州市  长兴县   NaN  制造业[C]  纺织业[17]  化纤织造及印染精加工[175]   

              HYMD4       SZDS    ...    SCL_BYZLJ SCL_QNBY SCL_QNBYZLJ  \
0      化纤织造加工[1751]  湖州市[3305]    ...          0.0    240.0       240.0   

  XSL_BY XSL_BYZLJ XSL_QNBY XSL_QNBYZLJ QMKCL  RKRQ      SJRQ  
0    0.0       0.0    240.0       240.0   0.0   NaN  201801.0  

[1 rows x 29 columns]

In [78]:
df_XWQY_CPXX.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147005 entries, 0 to 147004
Data columns (total 29 columns):
ZH             135230 non-null object
MC             147005 non-null object
DQ_S           146791 non-null object
DQ_Q           145070 non-null object
DQ_XZ          12525 non-null object
HYDM1          135499 non-null object
HYDM2          131754 non-null object
HYDM3          129691 non-null object
HYMD4          128481 non-null object
SZDS           134270 non-null object
SZDQX          133044 non-null object
SZDZJ          1698 non-null object
ZCLX           132696 non-null object
SFGS           127913 non-null object
GSGM           129402 non-null object
CPMC           127895 non-null object
CPDM           56841 non-null object
JLDW           126776 non-null object
SCL_BY         115029 non-null float64
SCL_BYZLJ      116865 non-null float64
SCL_QNBY       115377 non-null float64
SCL_QNBYZLJ    116436 non-null float64
XSL_BY         114515 non-null float64
XSL_BYZLJ     

In [79]:
df_XWQY_CPXX_JS = df_XWQY_CPXX.drop([
    'ZCLX','ZH', 'MC', 'DQ_S', 'DQ_Q', 'DQ_XZ', 'HYDM1', 'HYDM2', 'HYDM3', 'HYMD4',
    'SZDS', 'SZDQX', 'SZDZJ','CPMC','CPDM','JLDW','RKRQ'
], 1)
GSGM_MAP = {
    '微型企业':1,
    '小型企业':2,
    '中型企业':3,
    '大型企业':4,
    0:0
}
SFGS_MAP = {
    '是':2,
    '否':1,
    0:0
}

df_XWQY_CPXX_JS['SFGS'] = df_XWQY_CPXX_JS['SFGS'].fillna(0)
df_XWQY_CPXX_JS['GSGM'] = df_XWQY_CPXX_JS['GSGM'].fillna(0)
df_XWQY_CPXX_JS['SCL_BY'] = df_XWQY_CPXX_JS['SCL_BY'].fillna(0)
df_XWQY_CPXX_JS['SCL_BYZLJ'] = df_XWQY_CPXX_JS['SCL_BYZLJ'].fillna(0)
df_XWQY_CPXX_JS['SCL_QNBY'] = df_XWQY_CPXX_JS['SCL_QNBY'].fillna(0)
df_XWQY_CPXX_JS['SCL_QNBYZLJ'] = df_XWQY_CPXX_JS['SCL_QNBYZLJ'].fillna(0)
df_XWQY_CPXX_JS['XSL_BY'] = df_XWQY_CPXX_JS['XSL_BY'].fillna(0)
df_XWQY_CPXX_JS['XSL_BYZLJ'] = df_XWQY_CPXX_JS['XSL_BYZLJ'].fillna(0)
df_XWQY_CPXX_JS['XSL_QNBY'] = df_XWQY_CPXX_JS['XSL_QNBY'].fillna(0)
df_XWQY_CPXX_JS['XSL_QNBYZLJ'] = df_XWQY_CPXX_JS['XSL_QNBYZLJ'].fillna(0)
df_XWQY_CPXX_JS['QMKCL'] = df_XWQY_CPXX_JS['QMKCL'].fillna(0)
df_XWQY_CPXX_JS['QMKCL'] = df_XWQY_CPXX_JS['QMKCL'].fillna(0)

df_XWQY_CPXX_JS['GSGM'] = df_XWQY_CPXX_JS['GSGM'].map(GSGM_MAP)
df_XWQY_CPXX_JS['SFGS'] = df_XWQY_CPXX_JS['SFGS'].map(SFGS_MAP)


In [80]:
print(df_XWQY_CPXX_JS.shape)
df_XWQY_CPXX_JS.info()

(147005, 12)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 147005 entries, 0 to 147004
Data columns (total 12 columns):
SFGS           147005 non-null int64
GSGM           147005 non-null int64
SCL_BY         147005 non-null float64
SCL_BYZLJ      147005 non-null float64
SCL_QNBY       147005 non-null float64
SCL_QNBYZLJ    147005 non-null float64
XSL_BY         147005 non-null float64
XSL_BYZLJ      147005 non-null float64
XSL_QNBY       147005 non-null float64
XSL_QNBYZLJ    147005 non-null float64
QMKCL          147005 non-null float64
SJRQ           147004 non-null float64
dtypes: float64(10), int64(2)
memory usage: 13.5 MB


In [81]:
df_XWQY_CPXX_JS.head(1)

SFGS  GSGM  SCL_BY  SCL_BYZLJ  SCL_QNBY  SCL_QNBYZLJ  XSL_BY  XSL_BYZLJ  \
0     2     2     0.0        0.0     240.0        240.0     0.0        0.0   

   XSL_QNBY  XSL_QNBYZLJ  QMKCL      SJRQ  
0     240.0        240.0    0.0  201801.0

In [82]:
##删除错误数据
df_XWQY_CPXX_JS.isnull().any()
df_XWQY_CPXX_JS['SJRQ'] = df_XWQY_CPXX_JS['SJRQ'].fillna(9999)
drop_list = df_XWQY_CPXX_JS[(df_XWQY_CPXX_JS['SJRQ']==9999)].index.tolist()
df_XWQY_CPXX_JS[df_XWQY_CPXX_JS.isnull().values==True]
df_XWQY_CPXX_JS = df_XWQY_CPXX_JS.drop(drop_list)
df_XWQY_CPXX_JS.shape

(147004, 12)

In [83]:
#增加是否停产标志

def sftc(x):
    if x >0 :
        return 1
    else:
        return 0
pd_sftc = df_XWQY_CPXX_JS['SCL_BY'].apply(lambda x:sftc(x))
df_XWQY_CPXX_JS['SFTC'] = pd_sftc

In [84]:
df_XWQY_CPXX_JS.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 147004 entries, 0 to 147004
Data columns (total 13 columns):
SFGS           147004 non-null int64
GSGM           147004 non-null int64
SCL_BY         147004 non-null float64
SCL_BYZLJ      147004 non-null float64
SCL_QNBY       147004 non-null float64
SCL_QNBYZLJ    147004 non-null float64
XSL_BY         147004 non-null float64
XSL_BYZLJ      147004 non-null float64
XSL_QNBY       147004 non-null float64
XSL_QNBYZLJ    147004 non-null float64
QMKCL          147004 non-null float64
SJRQ           147004 non-null float64
SFTC           147004 non-null int64
dtypes: float64(10), int64(3)
memory usage: 15.7 MB


In [85]:
#归一化
# from sklearn.preprocessing import MinMaxScaler
# minMax = MinMaxScaler()
# df_XWQY_CPXX_JS = minMax.fit_transform(df_XWQY_CPXX_JS)
# print(df_XWQY_CPXX_JS)
df_XWQY_CPXX_JS.head(10)

SFGS  GSGM   SCL_BY  SCL_BYZLJ  SCL_QNBY  SCL_QNBYZLJ   XSL_BY  XSL_BYZLJ  \
0     2     2      0.0        0.0     240.0        240.0      0.0        0.0   
1     1     2    360.0      360.0     100.0        100.0    360.0      360.0   
2     1     1    944.0      944.0    4223.0       4223.0    944.0      944.0   
3     2     1  16569.0    16569.0    9357.0       9357.0  16569.0    16569.0   
4     0     0  15184.0    15184.0   15471.0      15471.0  15184.0    15184.0   
5     2     2  49230.0    49230.0   36102.0      36102.0  46550.0    46550.0   
6     1     1   1232.0     1232.0    1600.0       1600.0   1232.0     1232.0   
7     2     1    884.0      884.0     324.0        324.0   1041.0     1041.0   
8     0     1    549.0      549.0     570.0        570.0    549.0      549.0   
9     2     2   2013.0     3253.0    5021.0       5021.0   1199.0     1646.0   

   XSL_QNBY  XSL_QNBYZLJ   QMKCL      SJRQ  SFTC  
0     240.0        240.0     0.0  201801.0     0  
1     100.0        100.0     0.0  201801.0     1  
2    4223.0       4223.0     0.0  201801.0     1  
3    9357.0       9357.0     0.0  201801.0     1  
4   15471.0      15471.0     0.0  201801.0     1  
5   32380.0      32380.0  2120.0  201801.0     1  
6    1600.0       1600.0     0.0  201801.0     1  
7     268.0        268.0  1047.0  201801.0     1  
8     570.0        570.0     0.0  201801.0     1  
9    5021.0       5021.0  1607.0  201801.0     1

In [283]:
#单值定义
%matplotlib qt
tf.reset_default_graph()
df_XWQY_CPXX_JS = df_XWQY_CPXX_JS.astype(float)
train_x = df_XWQY_CPXX_JS['SFTC'][0:900]
train_y = df_XWQY_CPXX_JS['SFTC'][0:900]

print('X:', train_x.shape)  # (506, 1)
# print(x[::100])
print('Y:', train_y.shape)
# print(y[::100])
# 数据标准化
# ss_x = preprocessing.StandardScaler()
# train_x = ss_x.fit_transform(y.values.reshape(-1, 1))
# ss_y = preprocessing.StandardScaler()
# train_y = ss_y.fit_transform(y.values.reshape(-1, 1))

BATCH_START = 0  # 建立 batch data 时候的 index
TIME_STEPS = 10  # backpropagation through time 的 time_steps
BATCH_SIZE = 30
INPUT_SIZE = 1  
OUTPUT_SIZE = 1  
CELL_SIZE = 10  # RNN 的 hidden unit size
LR = 0.006  # learning rate
# 保存session状态的位置
save_dir = './jxw_save/ckpt/jxw'
# logs_path = './bst_save/log/'

# def get_batch_boston_10():
#     global train_x_list, train_y_list, BATCH_START, TIME_STEPS
#     train_x_list,train_y_list=[],[]
#     #(291, 10, 1)
#     for i in range(len(train_y)-TIME_STEPS-205):
#         x1=train_y[i:i+TIME_STEPS]
#         y1=train_y[i+1:i+TIME_STEPS+1]
#     #     x1=x1.reshape(30,10,-1)
#     #     y1=x1.reshape(30,10,-1)
#         train_x_list.append(x1.tolist())
#         train_y_list.append(y1.tolist()) 
#     train_x_np = np.array(train_x_list)
#     train_y_np = np.array(train_y_list)

#     seq = train_x_np
#     res = train_y_np
#     return [seq, res]


# def get_batch_boston_original():
#     global train_x, train_y, BATCH_START, TIME_STEPS
#     # 每次都是拿300行，13列的数据，但是起始点根据 BATCH_START
#     x_part1 = train_x[BATCH_START:BATCH_START + TIME_STEPS * BATCH_SIZE]
#     y_part1 = train_y[BATCH_START:BATCH_START + TIME_STEPS * BATCH_SIZE]
#     # 时间段= 0 300
#     # x_part1= (300, 13)
#     # 时间段= 10 310
#     # x_part1= (300, 13)
# #     print('时间段=', BATCH_START, BATCH_START + TIME_STEPS * BATCH_SIZE)
# #     print('x_part1=', x_part1.shape)
# #     print(BATCH_SIZE, TIME_STEPS, INPUT_SIZE)
#     # 转成 30 10 13的形状
#     seq = x_part1.reshape((BATCH_SIZE, TIME_STEPS, INPUT_SIZE))
#     res = y_part1.reshape((BATCH_SIZE, TIME_STEPS, 1))

#     BATCH_START += TIME_STEPS

#     # returned seq, res and xs: shape (batch, step, input)
#     #np.newaxis 用来增加一个维度 变为三个维度，第三个维度将用来存上一批样本的状态
#     return [seq, res]

#300
def get_batch_boston():
    global train_x_list, train_y_list, BATCH_START, TIME_STEPS
    train_x_list,train_y_list=[],[]
    for i in range(30):
        x1=train_y[i:i+TIME_STEPS*BATCH_SIZE]
        y1=train_y[i+1:i+TIME_STEPS*BATCH_SIZE+1]
#         y1=train_y[i:i+TIME_STEPS*BATCH_SIZE]
        x1=x1.reshape(30,10,-1)
        y1=y1.reshape(30,10)
        train_x_list.append(x1.tolist())
        train_y_list.append(y1.tolist()) 
    train_x_np = np.array(train_x_list)
    train_y_np = np.array(train_y_list)

    seq = train_x_np
    res = train_y_np
    
    return [seq, res]



# def get_batch():
#     global BATCH_START, TIME_STEPS
#     # xs shape (50batch, 20steps)
#     xs = np.arange(BATCH_START, BATCH_START + TIME_STEPS * BATCH_SIZE).reshape(
#         (BATCH_SIZE, TIME_STEPS)) / (10 * np.pi)
#     print('xs.shape=', xs.shape)
#     seq = np.sin(xs)
#     res = np.cos(xs)
#     BATCH_START += TIME_STEPS
#     # import matplotlib.pyplot as plt
#     # plt.plot(xs[0, :], res[0, :], 'r', xs[0, :], seq[0, :], 'b--')
#     # plt.show()
#     print('增加维度前:', seq.shape)
#     print(seq[:2])
#     print('增加维度后:', seq[:, :, np.newaxis].shape)
#     print(seq[:2])
#     # returned seq, res and xs: shape (batch, step, input)
#     #np.newaxis 用来增加一个维度 变为三个维度，第三个维度将用来存上一批样本的状态
#     return [seq[:, :, np.newaxis], res[:, :, np.newaxis], xs]


class LSTMRNN(object):
    def __init__(self, n_steps, input_size, output_size, cell_size,
                 batch_size):
        '''
        :param n_steps: 每批数据总包含多少时间刻度
        :param input_size: 输入数据的维度
        :param output_size: 输出数据的维度 如果是类似价格曲线的话，应该为1
        :param cell_size: cell的大小
        :param batch_size: 每批次训练数据的数量
        '''
        self.n_steps = n_steps
        self.input_size = input_size
        self.output_size = output_size
        self.cell_size = cell_size
        self.batch_size = batch_size
        with tf.name_scope('inputs'):
            self.xs = tf.placeholder(
                tf.float32, [None, n_steps, input_size], name='xs')  #xs 有三个维度
            self.ys = tf.placeholder(
#                 tf.float32, [None, n_steps, output_size], name='ys')  #ys 有三个维度
                tf.float32, [None, n_steps], name='ys')
        with tf.variable_scope('in_hidden'):
            self.add_input_layer()
        with tf.variable_scope('LSTM_cell'):
            self.add_cell()
        with tf.variable_scope('out_hidden'):
            self.add_output_layer()
        with tf.name_scope('cost'):
            self.compute_cost()
        with tf.name_scope('train'):
            self.train_op = tf.train.AdamOptimizer(LR).minimize(self.cost)

    #增加一个输入层
    def add_input_layer(self, ):
        # l_in_x:(batch*n_step, in_size),相当于把这个批次的样本串到一个长度1000的时间线上，每批次50个样本，每个样本20个时刻
        l_in_x = tf.reshape(
            self.xs, [-1, self.input_size], name='2_2D')  #-1 表示任意行数
        # Ws (in_size, cell_size)
        Ws_in = self._weight_variable([self.input_size, self.cell_size])
        # bs (cell_size, )
        bs_in = self._bias_variable([
            self.cell_size,
        ])
        # l_in_y = (batch * n_steps, cell_size)
        with tf.name_scope('Wx_plus_b'):
            l_in_y = tf.matmul(l_in_x, Ws_in) + bs_in
        # reshape l_in_y ==> (batch, n_steps, cell_size)
        self.l_in_y = tf.reshape(
            l_in_y, [-1, self.n_steps, self.cell_size], name='2_3D')

    #多时刻的状态叠加层 CELL
    def add_cell(self):
#         print('BATCH_SIZE',self.batch_size)
        lstm_cell = tf.nn.rnn_cell.BasicLSTMCell(
            self.cell_size, forget_bias=1.0, state_is_tuple=True)
        with tf.name_scope('initial_state'):
            self.cell_init_state = lstm_cell.zero_state(
                self.batch_size, dtype=tf.float32)
        #time_major=False 表示时间主线不是第一列batch
        self.cell_outputs, self.cell_final_state = tf.nn.dynamic_rnn(
            lstm_cell,
            self.l_in_y,
            initial_state=self.cell_init_state,
            time_major=False)

    # 增加一个输出层
    def add_output_layer(self):
        # shape = (batch * steps, cell_size)
        l_out_x = tf.reshape(
            self.cell_outputs, [-1, self.cell_size], name='2_2D')
        Ws_out = self._weight_variable([self.cell_size, self.output_size])
        bs_out = self._bias_variable([
            self.output_size,
        ])
        # shape = (batch * steps, output_size)
        with tf.name_scope('Wx_plus_b'):
            self.pred = tf.matmul(l_out_x, Ws_out) + bs_out  #预测结果
    
    # 计算损失
    def compute_cost(self):
        losses = tf.contrib.legacy_seq2seq.sequence_loss_by_example(
            [tf.reshape(self.pred, [-1], name='reshape_pred')],
            [tf.reshape(self.ys, [-1], name='reshape_target')],
            [tf.ones([self.batch_size * self.n_steps], dtype=tf.float32)],
            average_across_timesteps=True,
            softmax_loss_function=self.ms_error,
            name='losses')
        with tf.name_scope('average_cost'):
            self.cost = tf.div(
                tf.reduce_sum(losses, name='losses_sum'),
                self.batch_size,
                name='average_cost')
            tf.summary.scalar('cost', self.cost)

    def ms_error(self, labels, logits):
        return tf.square(tf.subtract(labels, logits))

    def _weight_variable(self, shape, name='weights'):
        initializer = tf.random_normal_initializer(
            mean=0.,
            stddev=1.,
        )
        return tf.get_variable(shape=shape, initializer=initializer, name=name)

    def _bias_variable(self, shape, name='biases'):
        initializer = tf.constant_initializer(0.1)
        return tf.get_variable(name=name, shape=shape, initializer=initializer)



X: (900,)
Y: (900,)


In [288]:
# 训练
tf.reset_default_graph()
if __name__ == '__main__':
    # 设置画布初始属性和内容

    fig = plt.figure(figsize=(20, 3))  # dpi参数指定绘图对象的分辨率，即每英寸多少个像素，缺省值为80
    axes = fig.add_subplot(1, 1, 1)
    line1, = axes.plot(train_y.values[19:-1], 'r', label='实际')
    plt.ion()
    plt.show()

    seq, res = get_batch_boston()
    costlist = []
    print('seq', seq.shape)
    print('res', res.shape)
    BATCH_SIZE = 30
    model = LSTMRNN(TIME_STEPS, INPUT_SIZE, OUTPUT_SIZE, CELL_SIZE, BATCH_SIZE)
    sess = tf.Session()
    merged = tf.summary.merge_all()
    writer = tf.summary.FileWriter("logs", sess.graph)
    # tf.initialize_all_variables() no long valid from
    # 2017-03-02 if using tensorflow >= 0.12
    sess.run(tf.global_variables_initializer())
    # relocate to the local dir and run this line to view it on Chrome (http://0.0.0.0:6006/):
    # $ tensorboard --logdir='logs'
    for j in range(100):  #训练200次
        pred_res = None
        # 300
        seq, res = get_batch_boston()
        #         print('seq',seq.shape)
        #        用于300
        #        影响折线图重合，数量10位移10，数量50，位移50
        for i in range(20):
            if i == 0:
#                 print('seq[i]',seq[i],seq[i].shape)
                #                 print('if')
                feed_dict = {
                    model.xs: seq[i],
                    model.ys: res[i],
                    # create initial state
                }
            else:
                #                 print('else')
                feed_dict = {
                    model.xs: seq[i],
                    model.ys: res[i],
                    model.cell_init_state:
                    state  # use last state as the initial state for this run
                }

            _, cost, state, pred = sess.run([
                model.train_op, model.cost, model.cell_final_state, model.pred
            ],
                                            feed_dict=feed_dict)
            pred_res = pred

            result = sess.run(merged, feed_dict)
            writer.add_summary(result, i)
            
        try:
            #             pass
            axes.lines.remove(line3)
            axes.lines.remove(line_c)
        except Exception:
            pass

        print('{0} cost: '.format(j), round(cost, 4))
        costlist.append(cost)
            
        line_c, = axes.plot(costlist,'y',label='cost')
        BATCH_START = 0  #从头再来一遍

#         handles, labels = plt.gca().get_legend_handles_labels()
# 返回是, 是一个Line2D的对象，无逗号是一个包含了Line2D的数组
#         line1, = axes.plot(
#             range(100), pred.flatten()[-100:], 'b--', label='rnn计算结果 '+str(j))
        line3, = axes.plot(pred.flatten(), 'b--', label='rnn计算结果 ' + str(j))
        axes.grid()
        fig.tight_layout()
        plt.legend(handles=[line1, line3,line_c])
        plt.title('递归神经网络')
        plt.pause(0.05)
    plt.ioff()
    plt.show()

    # 保存模型
    saver = tf.train.Saver()
    saver.save(
        sess,
        save_dir,
    )
    print('Model Trained and Saved')

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:78: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:79: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead


seq (30, 30, 10, 1)
res (30, 30, 10)
0 cost:  2.0597
1 cost:  1.9287
2 cost:  1.9138
3 cost:  1.9311
4 cost:  1.9021
5 cost:  1.8881
6 cost:  1.8567
7 cost:  1.8267
8 cost:  1.8316
9 cost:  1.7601
10 cost:  1.7735
11 cost:  1.8611
12 cost:  1.8915
13 cost:  1.7295
14 cost:  2.6104
15 cost:  1.8704
16 cost:  1.9159
17 cost:  1.8246
18 cost:  1.8007
19 cost:  1.7585
20 cost:  1.7524
21 cost:  1.7119
22 cost:  1.7706
23 cost:  1.7949
24 cost:  1.7251
25 cost:  2.0405
26 cost:  1.7548
27 cost:  1.8954
28 cost:  2.0537
29 cost:  1.9544
30 cost:  1.9099
31 cost:  1.8812
32 cost:  1.8642
33 cost:  1.8129
34 cost:  2.1167
35 cost:  1.9108
36 cost:  2.2624
37 cost:  1.8566
38 cost:  1.8239
39 cost:  1.8174
40 cost:  1.8882
41 cost:  1.8521
42 cost:  1.9084
43 cost:  2.2132
44 cost:  1.863
45 cost:  1.8447
46 cost:  2.122
47 cost:  1.8695
48 cost:  1.8375
49 cost:  2.1043
50 cost:  1.8473
51 cost:  1.9056
52 cost:  1.8536
53 cost:  1.8118
54 cost:  2.0983
55 cost:  1.7977
56 cost:  1.7886
57 cos

In [285]:
# 预测 300
%matplotlib qt
gen_length = 500
prime_word = '1'
loaded_graph = tf.Graph()
tf.reset_default_graph()
seq, res = get_batch_boston()
# BATCH_SIZE  = 1 
#改变 cell 的尺寸 和 输入数据的尺寸一致
model = LSTMRNN(TIME_STEPS, INPUT_SIZE, OUTPUT_SIZE, CELL_SIZE, 1)
saver = tf.train.Saver()
fig = plt.figure(figsize=(20, 3))  # dpi参数指定绘图对象的分辨率，即每英寸多少个像素，缺省值为80
axes = fig.add_subplot(1, 1, 1)
# train_y1 = train_y[190:490]
# train_y2 = train_y[0:300]
# train_y3 = train_y[0:506]
line5, = axes.plot(train_y, 'y', label='实际5')
plt.ion()
plt.show()
print('seq', seq.shape)
with tf.Session() as sess:
    # 加载保存过的session
    #     loader = tf.train.import_meta_graph(save_dir + '.meta')
    saver.restore(sess, './jxw_save/ckpt/jxw')
    #取训练集的最后一行，作为开始
#     prev_seq=train_x[-1]
#     prev_seq = seq[-1]
    
    prev_seq = np.array([seq.reshape(-1,10,1)[0].tolist()])
    predict=np.array([])
    for i in range(20):
        if i == 0:
#             print('if')
            feed_dict = {
                # create initial state
                model.xs: prev_seq
            }
        else:
#             print('else')
            feed_dict = {
                model.xs: prev_seq,
                # use last state as the initial state for this run
                model.cell_init_state: state 
            }
        state, next_seq = sess.run([model.cell_final_state, model.pred],
                               feed_dict=feed_dict)

#       添加到列表用于展现
#         predict = np.append(predict,next_seq[-1])
        predict = np.append(predict,next_seq)
#         print('predict',predict)
#         print(type(predict))
        
#         print('prev_seq',prev_seq.reshape([-1]).shape
#         print('prev_seq',prev_seq.shape)
#         print('next_seq',next_seq)
#         print('prev_seq[1:]',prev_seq[1:])
#         print('next_seq',next_seq[-1].shape)
        prev_seq = np.append(prev_seq.reshape(TIME_STEPS)[1:],next_seq.reshape(TIME_STEPS)[-1]).reshape(1,10,1)
        prev_seq = prev_seq.reshape(1,10,1)
#         print('prev_seq1',prev_seq,prev_seq.shape)
#         prev_seq = np.array([next_seq])
#         print('prev_seq2',np.array([next_seq]))
#         print('prev_seq',prev_seq.shape)
        line1, = axes.plot(predict, 'b--', label='rnn计算结果' + str(i))
#         line1, = axes.plot(next_seq, 'b--', label='rnn计算结果' + str(i))
        axes.grid()
        fig.tight_layout()
        plt.legend(handles=[line1, line5])
        plt.title('递归神经网络')
        plt.pause(0.5)

    BATCH_START = 0
    plt.ioff()
    plt.show()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:78: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:79: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead


seq (30, 30, 10, 1)
INFO:tensorflow:Restoring parameters from ./jxw_save/ckpt/jxw


In [ ]:
# 预测 10
%matplotlib qt
gen_length = 500
prime_word = '1'
loaded_graph = tf.Graph()
tf.reset_default_graph()
seq, res = get_batch_boston()
# BATCH_SIZE  = 1 
#改变 cell 的尺寸 和 输入数据的尺寸一致
model = LSTMRNN(TIME_STEPS, INPUT_SIZE, OUTPUT_SIZE, CELL_SIZE, 1)
saver = tf.train.Saver()
fig = plt.figure(figsize=(20, 3))  # dpi参数指定绘图对象的分辨率，即每英寸多少个像素，缺省值为80
axes = fig.add_subplot(1, 1, 1)
# train_y1 = train_y[190:490]
# train_y2 = train_y[0:300]
# train_y3 = train_y[0:506]
line5, = axes.plot(train_y.flatten(), 'y', label='实际5')
plt.ion()
plt.show()
print('seq', seq.shape)
with tf.Session() as sess:
    # 加载保存过的session
    #     loader = tf.train.import_meta_graph(save_dir + '.meta')
    saver.restore(sess, './bst_save/ckpt/bst')
    #取训练集的最后一行，作为开始
#     prev_seq=train_x[-1]
#     prev_seq = seq[-1]
    prev_seq = np.array([train_x_np[0][0].tolist()])
    print('prev_seq', prev_seq.shape)
    predict=[]
    for i in range(20):
        if i == 0:
#             print('if')
            feed_dict = {
                # create initial state
                model.xs: prev_seq
            }
        else:
#             print('else')
            feed_dict = {
                model.xs: prev_seq,
                # use last state as the initial state for this run
                model.cell_init_state: state 
            }
        state, next_seq = sess.run([model.cell_final_state, model.pred],
                               feed_dict=feed_dict)
#         print('next_seq',next_seq.shape)
#         print('next_seq',next_seq[-1])
#         print(type(predict))
        predict.append(next_seq[-1])
        
#         print('prev_seq',prev_seq.reshape([-1]).shape
#         print('prev_seq',prev_seq.shape)
#         print('next_seq',next_seq.shape)
#         print('next_seq',next_seq[-1].shape)
        prev_seq = np.vstack((prev_seq[1:],[next_seq]))

        line1, = axes.plot(predict, 'b--', label='rnn计算结果' + str(i))
        axes.grid()
        fig.tight_layout()
        plt.legend(handles=[line1, line5])
        plt.title('递归神经网络')
        plt.pause(0.5)

    BATCH_START = 0
    plt.ioff()
    plt.show()

In [235]:
a=np.arange(10).reshape(1,10, 1)
c=np.arange(10).reshape(10, 1)
print(a)
print()
print('a1',a[1:])
b = a.reshape(10)
d = a.reshape(10)
print('b',b)
print('b1',b[1:])
print('d',d)
print('d1',[d[-1]])
x = np.append(a.reshape(TIME_STEPS)[1:],b.reshape(TIME_STEPS)[-1]).reshape(1,10,1)
print(x)
# print(a.flatten()[-2:])

[[[0]
  [1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]]]

a1 []
b [0 1 2 3 4 5 6 7 8 9]
b1 [1 2 3 4 5 6 7 8 9]
d [0 1 2 3 4 5 6 7 8 9]
d1 [9]
[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]
  [7]
  [8]
  [9]
  [9]]]


In [10]:
a=np.arange(56).reshape(8,7)
#X取前5行的前三列（从1计数）
x=a[0:0+5,:3]
#Y取前5行的第4列（从0计数），并行转列
y=a[0:0+5,0,np.newaxis]
z=a[:,0]
print(a)
print(z)
zz =  (a[:,0] * 1000 / 60) - (a[:,4] + a[:,5] + a[:,6])
print(zz)
print('a',a[1:])
# print(x.shape)
# print(x)
# print(y.shape)
# print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]]
[ 0  7 14 21 28 35 42 49]
[-15.          80.66666667 176.33333333 272.         367.66666667
 463.33333333 559.         654.66666667]
a [[ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]]
